name: Server No Plugin | Playit

on:
  workflow_dispatch:
    inputs:
      phien_ban:
        description: 'nhập phiên bản ở đây lưu ý bạn phải ghi phiên bản từ 1.12.2 trở lên nha'
        required: true
      port:
        description: 'Nhập port bạn vào đây'
        required: true
      build:
        description: 'Nhập Build của papermc'
        required: true
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Cài File Spigot Và Chạy Server
      run: |
       wget https://api.papermc.io/v2/projects/paper/versions/${{github.event.inputs.phien_ban}}/builds/${{github.event.inputs.build}}/downloads/paper-${{github.event.inputs.phien_ban}}-${{github.event.inputs.build}}.jar 
       java -jar paper-${{github.event.inputs.phien_ban}}-${{github.event.inputs.build}}.jar &>/dev/null &
       rm -rf eula.txt
       wget -O eula.txt https://github.com/Snhvn/ServerMinecraftAction/raw/main/eula.txt
       rm -rf server.properties
       sudo mkdir /plugins/
       sudo wget /plugins/playit-minecraft-plugin.jar https://github.com/playit-cloud/playit-minecraft-plugin/releases/latest/download/playit-minecraft-plugin.jar
       java -jar paper-${{github.event.inputs.phien_ban}}-${{github.event.inputs.build}}.jar
       
