name: Server Minecraft 1.16.5 - 1.12.2 | Tailscale

on:
  workflow_dispatch:
    inputs:
      phien_ban:
        description: 'nhập phiên bản ở đây lưu ý bạn phải ghi phiên bản từ 1.16.5 - 1.12.3 nha'
        required: true
      server_icon:
        description: 'nhập link ảnh server vào'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Cài Tailscale , Ip Tailscale Và Cài File Với Chạy Sv Minecraft 
      run: |
       sudo apt update
       sudo apt install ufw
       sudo ufw allow 25565/tcp
       sudo ufw allow 25565/udp
       sudo ufw enable
       sudo ufw status
       curl -fsSL https://tailscale.com/install.sh | sh
       sudo tailscale up
       tailscale ip -4
       wget https://cdn.getbukkit.org/spigot/spigot-${{github.event.inputs.phien_ban}}.jar
       java -jar spigot-${{github.event.inputs.phien_ban}}.jar &>/dev/null &
       rm -rf eula.txt
       wget -O eula.txt https://github.com/Snhvn/ServerMinecraftAction/raw/main/eula.txt
       rm -rf server.properties
       wget -O server.properties https://github.com/Snhvn/ServerMinecraftAction/raw/main/server.properties
       java -jar spigot-${{github.event.inputs.phien_ban}}.jar
