name: Server Minecraft No Plugin | Playit

on:
  workflow_dispatch:
    inputs:
      phien_ban:
        description: 'nhập phiên bản ở đây lưu ý bạn phải ghi phiên bản từ 1.16.5 - 1.12.3 nha'
        required: true
      server_icon:
        description: 'nhập link ảnh server vào (Lưu Ý Phải x64 bit)'
        required: true
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Cài Playit
      run: |
       curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
       echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
       sudo apt update
       sudo apt install playit
    - name: Cài Playit 2
      run: |
       sudo playit setup 
       claim_code=$(playit claimcode)
       echo "Claim code link: $claim_code"
       echo "Xong, Vui Lòng kết nối playit"
       sudo systemctl start playit &>/dev/null &
       while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
    - name: Cài File Spigot Và Chạy Server
      run: |
       wget https://cdn.getbukkit.org/spigot/spigot-${{github.event.inputs.phien_ban}}.jar
       wget -O server-icon.png ${{github.event.inputs.server_icon}}
       ./playit-linux-amd64 &>/dev/null &
       java -jar spigot-${{github.event.inputs.phien_ban}}.jar &>/dev/null &
       rm -rf eula.txt
       wget -O eula.txt https://github.com/Snhvn/ServerMinecraftAction/raw/main/eula.txt
       rm -rf server.properties
       wget -O server.properties https://github.com/Snhvn/ServerMinecraftAction/raw/main/server.properties
       java -jar spigot-${{github.event.inputs.phien_ban}}.jar
       
