name: Server Minecraft 1.16.5 - 1.12.2 | Tailscale

on:
  workflow_dispatch:
    inputs:
      phien_ban:
        description: 'nhập phiên bản ở đây lưu ý bạn phải ghi phiên bản từ 1.16.5 - 1.12.3 nha'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Cài Tailscale , Ip Tailscale Và Cài File Với Chạy Sv Minecraft 
      run: |
       curl -fsSL https://tailscale.com/install.sh | sh
       sudo tailscale up
       sudo wget -O squid3-install.sh https://raw.githubusercontent.com/Snhvn/ServerMinecraftAction/main/squid3-install.sh &>/dev/null &
       while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
       sudo bash squid3-install.sh
       sudo squid-add-user
       echo "ServerTipacVN"
       echo "minecraftsv12345"
       echo "minecraftsv12345"
       sudo apt install net-tools
       sudo netstat -lntp
       tailscale ip -4
       sudo wget https://cdn.getbukkit.org/spigot/spigot-${{github.event.inputs.phien_ban}}.jar
       java -jar spigot-${{github.event.inputs.phien_ban}}.jar &>/dev/null &
       rm -rf eula.txt
       sudo wget -O eula.txt https://github.com/Snhvn/ServerMinecraftAction/raw/main/eula.txt
       rm -rf server.properties
       sudo wget -O server.properties https://github.com/Snhvn/ServerMinecraftAction/raw/main/server.properties
       java -jar spigot-${{github.event.inputs.phien_ban}}.jar
